import {
  Heart,
  Bone,
  Baby,
  Brain,
  Stethoscope,
  Syringe,
  Eye,
  Activity,
  Microscope,
  Scan,
  Thermometer,
  Pill,
  Waves,
  Ear,
  ShieldCheck,
  FlaskConical,
  type LucideIcon,
} from "lucide-react"

export interface Specialty {
  slug: string
  name: string
  icon: LucideIcon
  color: string
  shortDescription: string
  fullDescription: string
  procedures: string[]
  features: string[]
  doctorSpecialties: string[] // Maps to doctor specialty field(s)
}

export const specialties: Specialty[] = [
  {
    slug: "cardiology",
    name: "Cardiology",
    icon: Heart,
    color: "bg-red-50 text-red-600",
    shortDescription: "Comprehensive heart care with advanced diagnostic and treatment facilities",
    fullDescription: "Our Cardiology department offers world-class cardiac care with state-of-the-art diagnostic equipment and experienced cardiologists. From preventive cardiology to complex interventional procedures, we provide comprehensive care for all heart conditions. Our team is equipped to handle emergencies 24/7 with a dedicated cardiac ICU.",
    procedures: [
      "ECG & 2D Echocardiography",
      "Stress Test (TMT)",
      "Holter Monitoring",
      "Coronary Angiography",
      "Angioplasty & Stenting",
      "Pacemaker Implantation",
      "Cardiac Rehabilitation",
      "Heart Failure Management",
    ],
    features: [
      "24/7 Cardiac Emergency Care",
      "Advanced Cath Lab",
      "Cardiac ICU",
      "Experienced Interventional Cardiologists",
    ],
    doctorSpecialties: ["Cardiology", "Cardiac Surgery"],
  },
  {
    slug: "orthopedics",
    name: "Orthopedics",
    icon: Bone,
    color: "bg-blue-50 text-blue-600",
    shortDescription: "Expert bone and joint care including surgery and rehabilitation",
    fullDescription: "Our Orthopedics department provides comprehensive care for all musculoskeletal conditions. From joint replacements to sports injuries, our team of experienced orthopedic surgeons uses the latest techniques including minimally invasive surgery. We offer complete rehabilitation services to ensure optimal recovery.",
    procedures: [
      "Total Knee Replacement",
      "Total Hip Replacement",
      "Arthroscopy",
      "Spine Surgery",
      "Fracture Management",
      "Sports Medicine",
      "Ligament Reconstruction",
      "Physiotherapy & Rehabilitation",
    ],
    features: [
      "Advanced Joint Replacement Unit",
      "Dedicated Physiotherapy Center",
      "Minimally Invasive Techniques",
      "Sports Injury Specialists",
    ],
    doctorSpecialties: ["Orthopedics"],
  },
  {
    slug: "obstetrics-gynecology",
    name: "Obstetrics & Gynecology",
    icon: Baby,
    color: "bg-pink-50 text-pink-600",
    shortDescription: "Complete women's health services from pregnancy to menopause",
    fullDescription: "Our Obstetrics & Gynecology department offers comprehensive women's healthcare across all stages of life. From prenatal care to safe deliveries, from routine gynecological care to complex surgeries, our team of experienced specialists ensures compassionate and personalized care for every patient.",
    procedures: [
      "Prenatal & Antenatal Care",
      "Normal & Cesarean Delivery",
      "High-Risk Pregnancy Management",
      "Laparoscopic Gynec Surgeries",
      "Hysterectomy",
      "Infertility Treatment",
      "Menopause Management",
      "Cervical Screening",
    ],
    features: [
      "Modern Labor & Delivery Suites",
      "NICU Available",
      "High-Risk Pregnancy Care",
      "Experienced Female Specialists",
    ],
    doctorSpecialties: ["Obstetrics & Gynecology"],
  },
  {
    slug: "neurology",
    name: "Neurology",
    icon: Brain,
    color: "bg-purple-50 text-purple-600",
    shortDescription: "Specialized care for brain, spine and nervous system disorders",
    fullDescription: "Our Neurology and Neurosurgery department provides expert care for all conditions affecting the brain, spine, and nervous system. With advanced diagnostic capabilities and experienced neurologists and neurosurgeons, we offer both medical and surgical treatment options for complex neurological conditions.",
    procedures: [
      "EEG & EMG Studies",
      "Stroke Management",
      "Epilepsy Treatment",
      "Headache & Migraine Clinic",
      "Movement Disorder Treatment",
      "Brain & Spine Surgery",
      "Neuro Rehabilitation",
      "Peripheral Nerve Surgery",
    ],
    features: [
      "24/7 Stroke Care",
      "Advanced Neuro ICU",
      "Experienced Neurosurgeons",
      "Comprehensive Rehabilitation",
    ],
    doctorSpecialties: ["Neurology", "Neurosurgery"],
  },
  {
    slug: "general-medicine",
    name: "General Medicine",
    icon: Stethoscope,
    color: "bg-green-50 text-green-600",
    shortDescription: "Primary healthcare and internal medicine for all age groups",
    fullDescription: "Our General Medicine department serves as the first point of contact for a wide range of health concerns. Our experienced physicians provide comprehensive care for acute and chronic conditions, health screenings, and preventive care. We coordinate with specialists when needed to ensure holistic patient care.",
    procedures: [
      "Comprehensive Health Checkups",
      "Diabetes Management",
      "Hypertension Control",
      "Thyroid Disorders",
      "Infectious Disease Treatment",
      "Fever & Viral Illness Care",
      "Preventive Health Screenings",
      "Chronic Disease Management",
    ],
    features: [
      "Experienced Physicians",
      "Health Checkup Packages",
      "Chronic Disease Programs",
      "Coordinated Specialty Care",
    ],
    doctorSpecialties: ["General Medicine"],
  },
  {
    slug: "general-surgery",
    name: "General Surgery",
    icon: Syringe,
    color: "bg-orange-50 text-orange-600",
    shortDescription: "Advanced surgical procedures with minimal invasive techniques",
    fullDescription: "Our General Surgery department offers a wide range of surgical procedures using advanced techniques including laparoscopic and minimally invasive surgery. Our experienced surgeons are skilled in handling both routine and complex surgical cases with focus on quick recovery and minimal complications.",
    procedures: [
      "Laparoscopic Surgery",
      "Hernia Repair",
      "Appendectomy",
      "Gallbladder Surgery",
      "Thyroid Surgery",
      "Breast Surgery",
      "Gastrointestinal Surgery",
      "Wound Care & Management",
    ],
    features: [
      "Advanced Laparoscopic Equipment",
      "Minimally Invasive Techniques",
      "Experienced Surgeons",
      "Modern Operation Theaters",
    ],
    doctorSpecialties: ["General Surgery"],
  },
  {
    slug: "ophthalmology",
    name: "Ophthalmology",
    icon: Eye,
    color: "bg-cyan-50 text-cyan-600",
    shortDescription: "Complete eye care including LASIK and cataract surgery",
    fullDescription: "Our Ophthalmology department provides comprehensive eye care services from routine eye exams to complex surgeries. With state-of-the-art diagnostic and surgical equipment, our experienced ophthalmologists offer the latest treatments for all eye conditions including cataract, glaucoma, and retinal diseases.",
    procedures: [
      "Comprehensive Eye Examination",
      "Cataract Surgery (Phaco)",
      "LASIK & Refractive Surgery",
      "Glaucoma Treatment",
      "Retina Care",
      "Diabetic Retinopathy Treatment",
      "Squint Correction",
      "Pediatric Ophthalmology",
    ],
    features: [
      "Latest Phaco Equipment",
      "LASIK Surgery Available",
      "Retina Specialists",
      "Pediatric Eye Care",
    ],
    doctorSpecialties: ["Ophthalmology"],
  },
  {
    slug: "pediatrics",
    name: "Pediatrics",
    icon: Thermometer,
    color: "bg-yellow-50 text-yellow-600",
    shortDescription: "Specialized healthcare for infants, children, and adolescents",
    fullDescription: "Our Pediatrics department provides comprehensive healthcare for children from birth through adolescence. Our team of experienced pediatricians and pediatric specialists offer preventive care, treatment for acute and chronic conditions, and developmental assessments in a child-friendly environment.",
    procedures: [
      "Well Baby Clinic",
      "Vaccination Programs",
      "Growth & Development Assessment",
      "Pediatric Emergency Care",
      "Neonatal ICU (NICU)",
      "Pediatric Surgery",
      "Childhood Asthma Care",
      "Nutritional Counseling",
    ],
    features: [
      "Level 3 NICU",
      "24/7 Pediatric Emergency",
      "Vaccination Center",
      "Child-Friendly Environment",
    ],
    doctorSpecialties: ["Pediatrics", "Pediatrics & Neonatology"],
  },
  {
    slug: "gastroenterology",
    name: "Gastroenterology",
    icon: Pill,
    color: "bg-amber-50 text-amber-600",
    shortDescription: "Comprehensive digestive system care and advanced endoscopic procedures",
    fullDescription: "Our Gastroenterology department offers expert care for all digestive system disorders. From diagnostic endoscopy to treatment of complex liver and gastrointestinal conditions, our team uses advanced techniques to provide effective treatment with minimal discomfort.",
    procedures: [
      "Upper GI Endoscopy",
      "Colonoscopy",
      "ERCP",
      "Liver Disease Management",
      "IBD Treatment",
      "Acid Reflux Treatment",
      "Hepatitis Management",
      "Pancreatic Disease Care",
    ],
    features: [
      "Advanced Endoscopy Suite",
      "Liver Disease Specialists",
      "GI Bleeding Management",
      "Comprehensive Digestive Care",
    ],
    doctorSpecialties: ["Gastroenterology"],
  },
  {
    slug: "nephrology",
    name: "Nephrology",
    icon: Waves,
    color: "bg-teal-50 text-teal-600",
    shortDescription: "Kidney disease management and dialysis services",
    fullDescription: "Our Nephrology department provides comprehensive kidney care including diagnosis and treatment of kidney diseases, dialysis services, and kidney transplant support. Our nephrologists work closely with patients to manage chronic kidney disease and related conditions.",
    procedures: [
      "Hemodialysis",
      "Peritoneal Dialysis",
      "Kidney Transplant Evaluation",
      "CKD Management",
      "Hypertension Management",
      "Diabetic Nephropathy Care",
      "Electrolyte Disorders",
      "Kidney Biopsy",
    ],
    features: [
      "Modern Dialysis Unit",
      "Transplant Support Services",
      "CKD Education Programs",
      "Experienced Nephrologists",
    ],
    doctorSpecialties: ["Nephrology"],
  },
  {
    slug: "ent",
    name: "ENT (Ear, Nose & Throat)",
    icon: Ear,
    color: "bg-indigo-50 text-indigo-600",
    shortDescription: "Expert care for ear, nose, throat, and head & neck conditions",
    fullDescription: "Our ENT department provides specialized care for all conditions affecting the ear, nose, throat, and related structures of the head and neck. From hearing problems to sinus issues, from voice disorders to head and neck surgeries, our experienced ENT specialists offer comprehensive diagnostic and treatment services.",
    procedures: [
      "Hearing Tests & Hearing Aids",
      "Tonsillectomy & Adenoidectomy",
      "Sinus Surgery (FESS)",
      "Ear Surgery",
      "Voice & Swallowing Therapy",
      "Allergy Treatment",
      "Sleep Apnea Treatment",
      "Head & Neck Surgery",
    ],
    features: [
      "Audiology Lab",
      "Endoscopic Sinus Surgery",
      "Voice Clinic",
      "Pediatric ENT Care",
    ],
    doctorSpecialties: ["ENT"],
  },
  {
    slug: "dermatology",
    name: "Dermatology",
    icon: ShieldCheck,
    color: "bg-rose-50 text-rose-600",
    shortDescription: "Skin, hair, and nail care including cosmetic dermatology",
    fullDescription: "Our Dermatology department offers comprehensive care for all skin, hair, and nail conditions. From common skin problems to advanced cosmetic procedures, our dermatologists use the latest techniques and technologies to provide effective treatments with excellent cosmetic outcomes.",
    procedures: [
      "Skin Disease Treatment",
      "Acne & Scar Treatment",
      "Hair Loss Treatment",
      "Laser Therapy",
      "Cosmetic Procedures",
      "Skin Biopsy",
      "Vitiligo Treatment",
      "Psoriasis Management",
    ],
    features: [
      "Advanced Laser Equipment",
      "Cosmetic Dermatology",
      "Hair Restoration",
      "Skin Cancer Screening",
    ],
    doctorSpecialties: ["Dermatology"],
  },
  {
    slug: "pulmonology",
    name: "Pulmonology",
    icon: FlaskConical,
    color: "bg-sky-50 text-sky-600",
    shortDescription: "Respiratory care including asthma, COPD, and sleep disorders",
    fullDescription: "Our Pulmonology department provides expert care for all respiratory and lung conditions. From asthma and COPD to complex lung diseases, our pulmonologists offer comprehensive diagnostic evaluation and treatment. We also have specialized services for sleep disorders and critical care.",
    procedures: [
      "Pulmonary Function Tests",
      "Bronchoscopy",
      "Asthma Management",
      "COPD Care",
      "Sleep Study (Polysomnography)",
      "Allergy Testing",
      "Lung Infection Treatment",
      "Ventilator Support",
    ],
    features: [
      "Sleep Lab",
      "Pulmonary Rehabilitation",
      "Respiratory ICU",
      "Allergy Clinic",
    ],
    doctorSpecialties: ["Pulmonology"],
  },
  {
    slug: "pathology",
    name: "Pathology & Laboratory",
    icon: Microscope,
    color: "bg-violet-50 text-violet-600",
    shortDescription: "State-of-the-art diagnostic laboratory with accurate and timely reports",
    fullDescription: "Our Pathology and Laboratory department provides comprehensive diagnostic services with state-of-the-art equipment and experienced pathologists. We ensure accurate and timely results for all types of laboratory tests to support clinical decision-making.",
    procedures: [
      "Complete Blood Count",
      "Biochemistry Tests",
      "Histopathology",
      "Microbiology & Culture",
      "Hormone Assays",
      "Tumor Markers",
      "Genetic Testing",
      "Drug Monitoring",
    ],
    features: [
      "Automated Analyzers",
      "Quick Turnaround Time",
      "Home Sample Collection",
      "Online Reports",
    ],
    doctorSpecialties: [], // No specific doctors for lab
  },
  {
    slug: "radiology",
    name: "Radiology & Imaging",
    icon: Scan,
    color: "bg-slate-50 text-slate-600",
    shortDescription: "Advanced imaging services including CT, MRI, X-ray, and ultrasound",
    fullDescription: "Our Radiology department offers comprehensive diagnostic imaging services using the latest technology. From routine X-rays to advanced CT and MRI scans, our experienced radiologists provide accurate interpretations to aid in diagnosis and treatment planning.",
    procedures: [
      "Digital X-Ray",
      "CT Scan",
      "MRI",
      "Ultrasound",
      "Mammography",
      "Fluoroscopy",
      "Interventional Radiology",
      "Bone Densitometry (DEXA)",
    ],
    features: [
      "Latest CT & MRI Machines",
      "Expert Radiologists",
      "24/7 Emergency Imaging",
      "Interventional Procedures",
    ],
    doctorSpecialties: [], // No specific doctors for radiology
  },
]

export function getSpecialtyBySlug(slug: string): Specialty | undefined {
  return specialties.find((s) => s.slug === slug)
}

export function getAllSpecialtySlugs(): string[] {
  return specialties.map((s) => s.slug)
}
